# Generated by Django 2.2.4 on 2019-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='image',
            field=models.ImageField(default='D:\\Vishnu Personal\\gitkraken_repos\\contacts_django_rest_api\\media\\default\\default.png', upload_to='D:\\Vishnu Personal\\gitkraken_repos\\contacts_django_rest_api\\media\\images'),
        ),
    ]
