# Generated by Django 2.2.4 on 2019-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190904_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='image',
            field=models.ImageField(blank=True, default='D:\\Vishnu Personal\\gitkraken_repos\\contacts_django_rest_api\\mediadefault.png', upload_to='D:\\Vishnu Personal\\gitkraken_repos\\contacts_django_rest_api\\media\\images'),
        ),
    ]
